---

## Start LeoFS
- hosts: localhost
  gather_facts: False
  name: Config Admin Tool
  roles:
      - { role: controller }

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Detach Node
        command: ./leofs-adm detach {{ hostvars['192.168.0.153']['leofs_module_nodename'] }}

- hosts: leo_storage
  name: Stop LeoStorages
  roles:
      - { role: leo_storage, control_leofs: "stop" }

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=10

- hosts: leo_storage
  name: Remove AVS Files LeoStorage
  roles:
      - { role: leo_storage, do_remove_avs: true }

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Rebalance Node
        command: ./leofs-adm rebalance
