---

## Start LeoFS
- hosts: localhost
  gather_facts: False
  name: Config Admin Tool
  roles:
      - { role: controller }

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Recover Node
      command: ./leofs-adm recover-node {{ hostvars['192.168.0.154']['leofs_module_nodename'] }}

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=5
