---
- hosts: localhost
  gather_facts: False
  name: Config Admin Tool
  roles:
      - { role: controller }

- hosts: leo_storage
  name: Stop LeoStorages
  roles:
      - { role: leo_storage, control_leofs: "stop" }

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=5

- hosts: leo_storage
  name: Remove AVS Files LeoStorage
  roles:
      - { role: leo_storage, do_remove_avs: true }

- hosts: leo_storage
  name: Start LeoStorages
  roles:
      - { role: leo_storage, control_leofs: "start" }

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=5
