---

## Start LeoFS
- hosts: localhost
  gather_facts: False
  name: Config Admin Tool
  roles:
      - { role: controller }

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Suspend Node
        command: ./leofs-adm resume {{ resume_node }}

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=30
